// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:cec55e7d-2e27-4e4d-800a-8924b3d36eb8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_hIDtJZZok",
    "aws_user_pools_web_client_id": "4219m8pdpbuqef2kt905gbuos4",
    "oauth": {
        "domain": "amplifyauthweb-local.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.d234hqv4cc8d2c.amplifyapp.com/signedin",
        "redirectSignOut": "https://master.d234hqv4cc8d2c.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
